In [1]:
import tensorflow as tf
import tensorflow_probability as tfp

## Problem formulation

Think, for example, about a situation where a New York taxi driver transports an art dealer to a great art auction that starts in 25 minutes. The art dealer promises a generous tip ($500) if she arrives there in time.

Normal distribution
`loc = mu` is the mean
`scale = sigma` is the std. deviation

In [3]:
# option 1
# μ_1 = 19 min but a high uncertainty (standard deviation of σ_1 = 12 min)
mu = 19
sigma = 12
limit_time = 25
dist = tfp.distributions.Normal(loc=mu, scale=sigma)
dist.cdf(limit_time)

<tf.Tensor: shape=(), dtype=float32, numpy=0.69146246>

In [4]:
# option 2
mu = 22
sigma = 2
dist = tfp.distributions.Normal(loc=mu, scale=sigma)
dist.cdf(limit_time)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9331928>

## From chapter notebook (nb_ch05_01)

In [5]:
dist = tfp.distributions.Normal(loc=1.0, scale=0.1)
print('sample   :', dist.sample(3).numpy()) #Samples 3 numbers
print('prob     :',dist.prob((0,1,2)).numpy()) #Calculates the probabilities for positions 0,1,2
print('log_prob :',dist.log_prob((0,1,2)).numpy()) #Same as above just log
print('cdf      :',dist.cdf((0,1,2)).numpy()) #Calculates the cummulative distributions
print('mean     :',dist.mean().numpy()) #Returns the mean of the distribution
print('stddev   :',dist.stddev().numpy())

sample   : [1.1861522 1.0398921 1.0175613]
prob     : [7.694609e-22 3.989423e+00 7.694609e-22]
log_prob : [-48.616352    1.3836466 -48.616352 ]
cdf      : [7.619854e-24 5.000000e-01 1.000000e+00]
mean     : 1.0
stddev   : 0.1


## Book example

In [11]:
d = tfp.distributions.Normal(loc=[3], scale=1.5)
x = d.sample(2)
px = d.prob(x)
print(x)
print(px)

tf.Tensor(
[[3.762074 ]
 [3.3802285]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[0.23375991]
 [0.25755265]], shape=(2, 1), dtype=float32)
